### ISSUE TITLE
Can't use bytes as indexed

### ISSUE THREAD

**Issue by hswick** [figs999/Ethereum#1]
Was running into this error when I was passing in data into storeBytes

Uncaught Error: Number can only safely store up to 53 bits

Ran into this issue.
https://github.com/trufflesuite/truffle/issues/405

I see that the issue is that you have bytes indexed data. Were you able to get around this problem?

**Comment by figs999** [comment]
You should be able to safely ignore that error message.

That error happens because of a truffle suite test case which is expecting
that you will want to be able to decode the indexed value from the log
bloom, but for the purposes of my data storage technique the indexed data
is redundant and is what let’s you efficiently determine the validity of a
message from the log bloom.

Cheers!

**Comment by EtherKr8** [comment]
Were you able to get this working within Truffle? 

I have been using Remix and it does not prevent you from doing something like this, but if there is no easy way to disable that test case within truffle, I'll take a look at getting it to be compatible.

**Comment by hswick** [comment]
I haven’t had a chance to mess with it more. I’m sure  it is fixable, but I
found that error to be rather intimidating :p
